"""
ABDSシステム - プロンプトテンプレートモジュール
AI分析用のプロンプトテンプレートを管理
"""

from .analysis_prompt import (
    CONTENT_ANALYSIS_PROMPT,
    IMAGE_CONTEXT_PROMPT,
    ABUSE_DETECTION_PROMPT,
    COPYRIGHT_ANALYSIS_PROMPT,
    COMMERCIAL_USE_PROMPT,
    UNAUTHORIZED_REPOST_PROMPT,
    MODIFICATION_DETECTION_PROMPT,
    AnalysisPromptBuilder
)

__all__ = [
    "CONTENT_ANALYSIS_PROMPT",
    "IMAGE_CONTEXT_PROMPT",
    "ABUSE_DETECTION_PROMPT",
    "COPYRIGHT_ANALYSIS_PROMPT",
    "COMMERCIAL_USE_PROMPT",
    "UNAUTHORIZED_REPOST_PROMPT",
    "MODIFICATION_DETECTION_PROMPT",
    "AnalysisPromptBuilder"
]